development:
  adapter: postgresql
  encoding: unicode
  database: wishlister
  pool: 5
  username: postgres
  password: velering

test:
  adapter: postgresql
  encoding: unicode
  database: wishlister
  pool: 5
  username: postgres
  password: velering

wishlister:
  adapter: postgresql
  encoding: unicode
  database: wishlister
  pool: 5
  username: postgres
  password: velering